main: me.dasetwas.Chars4Cars
name: Chars4Cars
version: 1.1
author: DasEtwas
description: Lets you drive cars in Minecraft!

commands:
   chars4cars:
      description: Shows info about the Plugin.
      aliases: [c4c, charsforcars]
      usage: /chars4cars <reload> | <info> | <perms> | <stats>
   givecar:
      description: Gives you a car.
      usage: /givecar <Name> <Power> <Mass> <Fuel> [Player]
   killcars:
      description: Kills specified cars.
      usage: /killcars <all> | <empty> | <soft>
   getitemname:
      description: Gets the name of the item that can be used in the config.
      usage: /getitemname
  
permissions:
   c4c.*:
      description: Grants access to all actions and commands of Chars4Cars
      children:
         c4c.createfuelstation: true
         c4c.dropoverride: true
         c4c.info: true
         c4c.owneroverride: true
         c4c.givecar: true
   c4c.dropoverride:
      description: Allows players in Gamemode Creative to get Car drops.
   c4c.givecar:
      description: Allows players to give them cars using /givecar.
   c4c.owneroverride:
      description: Allows players to destroy cars not owned by them.
   c4c.info:
      description: Allows players to use the /c4c [no arguments] command showing command help.
   c4c.createfuelstation:
      description: Allows the player to create Fuel Stations.

softdepend: [Vault]
depend: [ProtocolLib]
   
